### PR TITLE
Docker

### PR DESCRIPTION
**Pull request by hlbraddock**

### CODE REVIEW

**Comment by dmkov** [comment]
Hi guys,

This application was also updated in the same way as we did in other projects. Please review these changes and let me know if there is something that should be updated.

Thank you!

**Comment by dmkov** [comment]
Hi Matt,

I replaced all properties with environment variables for consistency and to avoid ambiguity with the project settings. 

There are no issues with properties mentioned in the file itself, however it was loaded in couple other places for error reporting and user authentication. 

Can you please double check commit [055d129](https://github.com/CruGlobal/pshr-listener/pull/12/commits/055d12929c0b0893f844e389300322a7edc61882) with extra attention? I wrapped environment variables into the property "user.{username}={password}" but source code there is inherited and embedded couple times so I would like to confirm that I did not miss anything.

**Comment by dmkov** [comment]
Hi Matt,

I have replaced ErrorEmailer with Red Egg integration and removed AuthenticationManager in the last commits. Please review changes when you have time and let me know if anything else should be updated there.

Thank you!

**Comment by mattdrees** [comment]
this is now deploying through jenkins fine and running at pshr-listener-stage.aws.cru.org.

**Pull request merged**
